# Default values for my-chart.
# Declare variables to be passed into your templates.
name: nginx-sample
replicaCount: 3

labels:
  app: nginx-sample-app

selectorLabels:
  app: nginx-sample
  version: v1

service:
  type: ClusterIP
  port: 80
  targetPort: http
  protocol: TCP
  name: http

autoscaling:
  enabled: true
  replicaCount: 1
